"""
Evernothing_UI — all HTML templates and CSS theme constants.
"""
from Evernothing_UI.templates import (
    STYLE, STYLE_STELLAR, STYLE_UNICORN, STYLE_STARTREK, STYLE_SHREK, STYLE_LOTR,
    T_FOLDERS, T_ADD_FOLDER, T_ADD_SUBFOLDER, T_RENAME_FOLDER,
    T_CHANGE_PASSWORD, T_DELETE_NOTE, T_EDIT_CONFIRM, T_NOTES,
    T_ADD, T_EDIT, T_LOGIN, T_REGISTER, T_SEARCH, T_DELETE_FOLDER,
    T_HISTORY, T_ADMIN_LOGIN, T_ADMIN_SESSIONS, T_ADMIN_DASHBOARD,
    T_ADMIN_EDIT_USER, T_ADMIN_EDIT_USER_CONFIRM, T_ADMIN_DELETE_USER,
    T_FORGOT_PASSWORD, T_RESET_PASSWORD, T_AUDIT_REPORT, T_SESSIONS,
    T_ADMIN_AUDIT_LOGS, T_ADMIN_S3_BACKUPS,
)
